services:
  - type: web
    name: telegramauthwebapp
    runtime: docker
    env: alpine
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    healthCheckPath: /api/health