server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: sa
    password:
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    username: FarEastCryptoBot
