server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d0qeieruibrs73ei1s7g-a:5432/users
    driverClassName: org.postgresql.Driver
    username: telegram_auth_wqr7_user
    password: OzAZ6QAz9QG7awmYqRE5Hi6cONXRU4Js
    hikari:
      maximum-pool-size: "5"
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    username: FarEastCryptoBot
