server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: TELEGRAM_SESSION
        http-only: true
        secure: true
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

  # Остальные настройки остаются без изменений
  datasource:
    url: jdbc:postgresql://dpg-d0s2jsq4d50c73b71s4g-a:5432/telegram_auth_db_user
    username: telegram_auth_db_user
    password: mwJR6KXoKyv2EvF7ITe1oUfb9AGoMl75
    hikari:
      maximum-pool-size: 5
  thymeleaf:
    cache: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    username: FarEastCryptoBot