# Server
server:
  port: 8080

# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: sa
    password:
  thymeleaf:
    cache: false

  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Telegram
telegram:
  bot:
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    username: FarEastCryptoBot
