FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

# Копируем только файлы, необходимые для установки зависимостей
COPY pom.xml .
COPY src ./src

# Собираем приложение
RUN mvn clean package -DskipTests

# Команда для запуска (используем точное имя файла)
CMD ["java", "-jar", "target/telegram-webauth.jar"]